# Source: https://github.com/amannn/action-semantic-pull-request

name: Semantic Pull Request

permissions:
  pull-requests: read

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Semantic Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Validate Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
